# - title: 
#   image:
#     src: /assets/img/project/default.jpg
#     alt: 
#   date: 
#   description: 
#   links:
#     repo: 
#     demo: 
#     blog:

- title: Comparative study of SLAM Backends — iSAM2 and Levenberg-Marquardt
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: Apr '24
  description: 
  links:
    repo: https://github.com/trunc8/slam-project
    demo: 
    blog: 

- title: Iterative Closest Points
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 


- title: Solvers
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 


- title: Extended Kalman Filter
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 


- title: Particle Filters
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 


- title: Vehicle Tracking using Lucas Kanade Forward Alignment Method
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: Mar '24 - Apr '24
  description: 
  links:
    repo: https://github.com/trunc8/vehicle-tracking-lucas-kanade-alignment
    demo: https://youtu.be/Kp99f36Dc38
    blog: 


- title: Tinder for Fashion
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: Oct '23
  description: 
  links:
    repo: https://github.com/trunc8/tinder_for_fashion
    demo: 
    blog: 

- title: Catching a moving target
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 


- title: High Degree of Freedom Planning
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 


- title: Symbolic Planning
  image:
    src: /assets/img/project/default.jpg
    alt: 
  date: 
  description: 
  links:
    repo: 
    demo: 
    blog: 





- title: Long Horizon Task Planning for Quadruped Robot
  image:
    src: /assets/img/project/task-planning-quadruped.png
    alt: 
  date: Sep '23 - Present
  description: We obtained quadruped controller using curriculum-based learning in Isaac Gym. We collected time & energy costs dataset for local motions and trained cost predictor as a multi-head convolutional NN. We demonstrated long horizon task planning with user-defined objective using A* search guided by the cost predictor
  links:
    # repo: https://github.com/trunc8/2D-footstep-planning
    # demo: https://github.com/trunc8/2D-footstep-planning#demo
    # blog: https://github.com/trunc8/2D-footstep-planning/blob/main/report.pdf

- title: Autonomous Quadruped in Unknown Cluttered Terrains
  image:
    src: /assets/img/project/darkbot.png
    alt: Darkbot image
  date: Sep '22 - Dec '23
  description: This was my MRSD Capstone Project at CMU with Prof. Sebastian Scherer, AirLab. The MRSD capstone is a three-semester long project with a budget of $5000 from MRSD + funding from sponsors. At the end of the project, our robot was able to explore unknown and cluttered disaster sites to search for trapped humans.
  links:
    blog: https://trunc8.github.io/2022/11/03/capstone-first-progress
  #   repo: https://github.com/trunc8/Dynamic-Octomap
    demo: https://youtu.be/iyLnfotGtfM

- title: Breadth vs Depth - Benchmarking Generalists and Specialists in Robot Agility Learning
  image:
    src: /assets/img/project/breadth-depth.png
    alt: 
  date: Sep '23 - Dec '23
  description: We trained specialist skills like jumping, climbing, and narrow beam walking. I implemented an RL+PPO-based Selector Policy to select the most effective specialist skill in varying environmental conditions. We compared its performance against a generalist policy trained on a combination of all skills.
  links:
    # repo: https://github.com/trunc8/2D-footstep-planning
    # demo: https://github.com/trunc8/2D-footstep-planning#demo
    # blog: https://github.com/trunc8/2D-footstep-planning/blob/main/report.pdf

- title: Quadruped Robot Challenge | ICRA '23, London
  image:
    src: /assets/img/project/qrc.png
    alt: 
  date: May '23 - Jun '23
  description: Deployed controller to Unitree Go1 & navigated challenge course using Beyond Visual Line-of-Sight teleoperation. Recovered from falls using pre-defined maneuvers and achieved the third position representing Carnegie Mellon.
  links:
    # repo: 
    demo: https://youtu.be/GlidNFKa-us
    # blog: 

- title: 2D Footstep Planning
  image:
    src: /assets/img/project/2D-footstep-planning.png
    alt: 
  date: Jan '23 - May '23
  description: Implementation of footstep planner for a biped robot on discontinuous 2D environments
  links:
    repo: https://github.com/trunc8/2D-footstep-planning
    demo: https://github.com/trunc8/2D-footstep-planning#demo
    blog: https://github.com/trunc8/2D-footstep-planning/blob/main/report.pdf

- title: Jenga Playing Manipulator Arm
  image:
    src: /assets/img/project/jenga.png
    alt: 
  date: Jan '23 - May '23
  description: Designed probe and grasp pipeline for the Franka Emika Panda robot to build Jenga tower
  links:
    # repo: https://github.com/trunc8/2D-footstep-planning
    demo: https://youtu.be/u-DxPaPN3sg
    # blog: https://github.com/trunc8/2D-footstep-planning/blob/main/report.pdf

- title: ROS2 RADI and single-robot warehouse exercise
  image:
    src: /assets/img/project/amazon-single-slam.gif
    alt: 
  date: Jun '21 - Aug '21
  description: Google Summer of Code project at JdeRobot. Built RADI 4 based on ROS2 Foxy, implemented BT (Behavior Tree) Navigator, and extended warehouse pick-and-delivery exercise to ROS2 web-based template
  links:
    repo: https://github.com/TheRoboticsClub/gsoc2021-Siddharth_Saha
    demo: https://youtu.be/RfW2hI_8j74
    blog: https://theroboticsclub.github.io/gsoc2021-Siddharth_Saha/milestones/2021/08/21/final-report

- title: Mapping Regions of Dynamic Activity & Building Dynamic-free 3D Occupancy Maps
  image:
    src: /assets/img/project/dynamic-octomap.png
    alt: 
  date: Jun '20 - Jul '21
  description: Bachelor's Thesis at IIT Bombay under Prof. Vachhani. Designed and implemented a novel clustering algorithm in ROS OctoMap to reject nodes with high dynamic activity
  links:
    repo: https://github.com/trunc8/Dynamic-Octomap
    demo: https://youtu.be/rUUqPmobm1k

- title: Quadruped Robot
  image:
    src: /assets/img/project/stride.png
    alt: 
  date: Dec '19 - May '21
  description: Founding member and Team Lead of an institute funded team to solve the urban search and rescue challenge -- RoboCup Rescue League. Simulated gait trajectory, and implemented sensor fusion between Intel D435 and IMU

- title: Hilti SLAM Challenge | IROS '21, Prague
  image:
    src: /assets/img/project/hilti.jpg
    alt: 
  date: Sep '21
  description: Explored Visual Inertial Odometry. Understood and calibrated Kannala-brandt camera model. Used VINS-Fusion. Calibrated IMU noise parameters using imu_utils on provided bag files
  links:
    blog: https://trunc8.github.io/2021/09/08/doc-hilti

- title: Robot Vision Scene Understanding Challenge | CVPR '21
  image:
    src: /assets/img/project/rvsu.jpg
    alt: 
  date: Mar '21 - Apr '21
  description: Implemented multiple approaches using Votenet, GroupFree3D, Votenet Ensemble. Trained Votenet model on subset of sunrgbd dataset. Trained YOLOv4 on subset of MS COCO dataset, and executed it in parallel to achieve higher confidence through a consensus mechanism
  links:
    repo: https://github.com/trunc8/robot-vision-scene-understanding-challenge
    blog: https://github.com/parth-shettiwar/3D-Object-Detection-and-Semantic-Map-Generation/blob/main/Presentation/Final_Presentation.pdf

- title: F1/10th — Autonomous Grand Prix | IROS ’20, Las Vegas
  image:
    src: /assets/img/project/f1tenth.png
    alt: 
  date: Oct '20
  description: Used Bernstein polynomial based local trajectory planner. Optimized global reference path using an OSQP solver. Implemented obstacle detection.

- title: Two-wheeled Self-Balancing Bot
  image:
    src: /assets/img/project/self-balancing-bot.jpg
    alt: 
  date: Aug '20 - Nov '20
  description: Demonstrates the inverted pendulum problem using a two-wheeled bot and input from gyroscope+accelerometer module
  links:
    demo: https://youtu.be/zCnvgg1dpSY
    blog: https://trunc8.github.io/2020/12/15/doc-self-balancing-bot

- title: Autonomous Drone Exploration
  image:
    src: /assets/img/project/interiit.png
    alt: 
  date: Mar '21
  description: (Team leader in *Inter IIT Tech Meet '21* ) Quadrotor simulation capable of navigating in a complex static environment by avoiding on-field obstacle-collision and reaching the target destination after its correct detection. 
  links:
    repo: https://github.com/trunc8/drdo-drone-challenge

- title: Multi-robot Capture of Non-adversarial Target
  image:
    src: /assets/img/project/mespp.png
    alt: 
  date: Mar '21 - Apr '21
  description: Capture of a moving target using Mixed Integer Linear Programming. Implementation from scratch of 'MILP Models for Multi-Robot Non-Adversarial Search' paper
  links:
    repo: https://github.com/trunc8/multirobot-efficient-search-path-planning
    blog: https://trunc8.github.io/2021/04/01/pr-mespp

- title: International Micromouse Challenge
  image:
    src: /assets/img/project/comp-imc.png
    alt: 
  date: Dec '20
  description: Reach from the corner square to the center of an unknown maze in the shortest time
  links:
    repo: https://github.com/trunc8/international-micromouse-techfest2020
    demo: https://youtu.be/PcbNQ-tVwQw?t=107
    blog: https://trunc8.github.io/2020/12/28/comp-imc

- title: Shortest Path in Maze using Reinforcement Learning
  image:
    src: /assets/img/project/gridworld_maze.png
    alt: 
  date: Oct '20 - Nov '20
  description: Modelled 2D maze as an MDP with appropriate states, actions, rewards & transition probabilities. Implemented Howard’s Policy Iteration, Value Iteration and Linear Programming to find best policy that minimizes number of steps between 2 given points while following constraints
  links:
    repo: https://github.com/trunc8/cs747-assignments

- title: Automated Graph Reader
  image:
    src: /assets/img/project/auto-graph-reader-demo.png
    alt: 
  date: Aug '20 - Nov '20
  description: Deployed live on Heroku server, the web-app accepts queries for y-values in simple input graphs. The solution is based on image processing, OCR, and a lot of algorithm design
  links:
    repo: https://github.com/trunc8/auto-graph-reader-webapp

- title: Optimization of vehicle suspension
  image:
    src: /assets/img/project/suspension.png
    alt: 
  date: Jan '21 - Apr '21
  description: Comparison of standard library functions and our own implementations of genetic algorithm, simulated annealing, and particle swarm optimization for the vehicle suspension optimization
  links:
    repo: https://github.com/trunc8/optimization-project

- title: Snippet-to-text Extraction
  image:
    src: /assets/img/project/snippet-to-text-demo.png
    alt: 
  date: Aug '20 - Nov '20
  description: Deployed live on Heroku server, the web-app allows you to read image snippets as continuous text
  links:
    repo: https://github.com/trunc8/snippet-to-text-webapp

- title: Panoramic Mosaicing
  image:
    src: /assets/img/project/panorama.jpg
    alt: 
  date: Mar '21
  description: Uses ORB feature extractor, Brute Force Matcher with Hamming Norm, and RANSAC algorithm to mosaic any number of input images
  links:
    repo: https://github.com/trunc8/panoramic-mosaicing

- title: Image Quilting
  image:
    src: /assets/img/project/image-quilting.png
    alt: 
  date: Sep '19 - Oct '19
  description: This achieves *Texture Transfer* using simple memoization-based Image Quilting technique (where people are nowadays using deep learning techniques). The *Texture Synthesis* implementation is useful for creating background in video games with cheap computation
  links:
    repo: https://github.com/trunc8/image-quilting

- title: Sudoku Solver Using Block Printing
  image:
    src: /assets/img/project/sudoku-block-printer.png
    alt: 
  date: Apr '18 - May '18
  description: Implemented a Raspian-based automated Machine to physically fill into any given unsolved Sudoku grid using computer-vision
  links:
    repo: https://github.com/trunc8/sudoku-solver-itsp-2018
    demo: https://youtu.be/3ukm6GfWYAw

- title: Ball Tracking using OpenCV and ROS
  image:
    src: /assets/img/project/ball-tracking.png
    alt: 
  date: Oct '20
  description: Python implementation of Ball tracking using OpenCV and CvBridge in ROS1
  links:
    repo: https://github.com/trunc8/ball-tracking-opencv-and-ros
    demo: https://youtu.be/zst5iFkaByQ

- title: Ricart-Agrawala Algorithm
  image:
    src: /assets/img/project/ricart-agrawal.png
    alt: 
  date: Aug '19 - Nov '19
  description: The Ricart-Agrawala algorithm provides an optimal solution to the problem of mutually exclusive access to a critical section in computer networks, whose nodes communicate only by messages and do not share memory
  links:
    repo: https://github.com/trunc8/ricart-agrawala-algorithm

- title: Wifi De-auth Attacker
  image:
    src: /assets/img/project/esp8266.jpg
    alt: 
  date: Mar '19
  description: Programmed ESP8266 (Wi-Fi microchip) to spoof an access point and send de-authentication frames, exploiting vulnerability in IEEE 802.11 standards of the absence of encryption for management frames
  links:
    # demo: 

- title: Gyro Brick Breaker
  image:
    src: /assets/img/project/gyro-brick-breaker.jpg
    alt: 
  date: Jul '18
  description: Led 5-membered team to develop hand-gesture controlled brick-breaking game coded in Processing IDE. One among 3 projects showcased at Undergraduate Freshmen Technical Orientation 2018
  links:
    demo: https://youtu.be/HFHVBlhADvA

- title: Conway’s Game of Life
  image:
    src: /assets/img/project/conway.png
    alt: 
  date: Apr '21
  description: Terminal based version of the hacker's favorite game. The source code is accompanied with unittesting. Developed as part of JdeRobot's GSoC Python Challenge
  links:
    repo: https://github.com/trunc8/conways-game-of-life

- title: Labyrinth CMake app
  image:
    src: /assets/img/project/labyrinth.png
    alt: 
  date: Apr '21
  description: CMakeLists based app to find the longest route in a text map. Developed as part of JdeRobot's GSoC C++ Challenge
  links:
    repo: https://github.com/trunc8/labyrinth-cmake-app
